### ISSUE TITLE
Simple DNSCrypt

### ISSUE THREAD

**Issue by Chaython** [pengelana/jp.tiar.app#1]
Is there anyway for me to validate that an encrypted DNS is being used?
Simple DNSCrypt set to secure only w/ automatic server selection
https://whoismydns.com/ resolves

DNS Server
172.104.93.80
Reverse DNS
jp.tiar.app
IP Owner (From ARIN)
Linode

So it's your server, how would I know if it's actually encrypted however?

Edit: According to https://www.cloudflare.com/ssl/encrypted-sni/ It's  using TLS 1.3 / DNScrypt however "Your browser did not encrypt the SNI when visiting this page."

**Comment by pengelana** [comment]
You can try to capture your traffic with tcpdump/wireshark.
